KEEPER31337/Homepage-Front

src/page/Board/BoardMain.jsx, src/page/Board/BoardView.jsx, src/page/Board/Components/TextEditer.jsx
- 모바일 화면에서의 컴포넌트 크기 비율 조정
- 모바일 화면에서의 write 페이지 버튼들 배치 조정
#12
=> [ 반응형 UI 수정 ]

src/page/SignIn/SignIn.jsx
=> feat) 로그인 엔터쳐도 로그인 되게

src/page/Game/Components/Roulette.jsx
- 포인트 부족 알림
- 횟수 제한 알림
- 로그인 필요 알림
#20
=> feat) Roulette 모달 띄워주기

src/page/Game/Components/Lotto.jsx
=> feat) Lotto 모달 띄워주기

src/page/SignUp/SignUp.jsx
=> fix) 회원가입 다크모드 수정

src/page/SignIn/Components/FindId.jsx, src/page/SignIn/Components/FindPassword.jsx, src/page/SignIn/SignIn.jsx, src/page/SignUp/SignUp.jsx
- 로그인/회원가입/아이디찾기/비밀번호찾기 페이지 => 로그인되어있다면 main으로 보내기
#44
=> feat)  로그인되어있다면 main으로 보내기

src/API/v1/member.js, src/page/Game/Components/Dice.jsx, src/page/Game/Components/Lotto.jsx, src/page/Game/Components/Roulette.jsx
=> feat) 게임 코드 수정

src/page/Board/Components/Gallary.jsx, src/page/Board/Components/Info.jsx, src/page/Board/Components/categoryMapper.js, src/page/Home/Component/Latest.jsx, src/page/Home/Component/Trends.jsx
- 메인페이지에서 트렌딩,최근글 열람할 때 카테고리 변경이 적용되도록 함
#12 , #16
=> fix:메인페이지에서 게시글에 접근 시 카테고리 변경이 적용되도록

src/shared/Component/SignInBoxMobile.jsx
- 모바일 버전 - 로그인, 회원가입 버튼 바꾸기
#19
=> fix) 모바일 버전 - 로그인, 회원가입 버튼 바꾸기

src/page/SignUp/SignUp.jsx
- 이메일  [영어, 숫자, '_'] 만 가능하도록 수정
아이디 : 영어, 숫자, '_'
비밀번호 : 영어, 숫자 조합 필수 + 특수문자 가능
이메일 : 영어, 숫자, '_'
이름 : 한글, 영어
닉네임 : 한글, 영어, 숫자
학번 : 숫자
#19
=> fix) 유효성 검사 - 이메일 수정

src/page/Board/Components/Comments.jsx, src/page/Board/Components/Table.jsx, src/page/Board/Components/TextEditer.jsx, src/page/Study/Components/AboutCard.jsx, src/page/Study/Components/Modals/ModifyStudy.jsx
=> Feature/게시판&스터디 버그 fix

src/API/v1/ctf.js
=> ctf팀 관련 api추가

src/page/CTF/admin/ChallengeAdmin.jsx, src/page/CTF/admin/Operation.jsx, src/page/CTF/admin/Submissions.jsx, yarn.lock
=> feat) 테두리 제거

src/API/v1/ctf.js, src/page/CTF/admin/ChallengeAdmin.jsx
=> feat) 문제 관리 페이지 ui + api

src/page/CTF/Components/ScoreBoardAnimation.jsx
- 애니메이션 - 1,2,3등 값 없을시 엑박 에러 고침
#143
=> feat) 스코어보드 에러 고침

src/page/CTF/Team.jsx
=> CTF 팀 페이지 다크모드 정용

src/API/v1/ctf.js, src/page/CTF/admin/ChallengeWrite.jsx
=> CTF 파일 업로드

src/page/CTF/Team.jsx, src/page/CTF/TeamJoin.jsx
- 이미 팀에 가입한 사람이 팀을 생성/가입하려하면 경고띄워주기
- 팀이 존재하지 않은 상태에서 팀페이지 들어가려고 하면 팀 페이지다르게 바꿔주기
(팀 가입 부탁드립니다! 라는 문장만 보임)
#144
=> feat) CTF 팀 페이지

src/page/CTF/Components/ChallengeModal.jsx
- flag제출 후 정답일때 바로 색 변환이 적용될 수 있도록 새로고침 함
#142
=> feat) flag 정답일 시 바로 색 변환 적용

src/page/CTF/Team.jsx
- 팀페이지에서 팀 이름/설명 안넣었을때 수정 안되도록 고침
#144
=> fix) 팀페이지에서 팀 이름/설명 안넣었을때 수정 안되도록 고침

src/API/v1/about.js, src/page/About/Component/Activity.jsx, src/page/About/Component/Excellence.jsx, src/page/About/Component/History.jsx, src/page/About/Component/Intro.jsx
- 백엔드 수정 사항 반영해서 동아리 소개글 에러 해결
=> fix) 동아리소개글 에러 해결

package-lock.json, package.json, src/page/Vote/Components/CheckBox.jsx, src/page/Vote/Components/CheckContent.jsx, src/page/Vote/Components/SubmitContentLG.jsx, src/page/Vote/Components/SubmitContentMD.jsx, src/page/Vote/Components/SubmitContentSM.jsx, src/page/Vote/Components/SubmitHeader.jsx, src/page/Vote/admin/Submissions.jsx, yarn.lock
=> feat: 후보자 등록 페이지

package-lock.json, package.json, src/page/Vote/Components/VoteDataScore.jsx, src/page/Vote/Components/WindowDimensions.jsx, src/page/Vote/ScoreBoard.jsx, yarn.lock
=> feat: 투표집계 페이지

src/page/Vote/Components/Submissions/GetContentData.jsx, src/page/Vote/Components/Submissions/RevisePeople.jsx, src/page/Vote/Components/Submissions/SubmitContent.jsx, src/page/Vote/admin/Submissions.jsx
=> feat: 인원관리 페이지

src/page/Vote/Components/ScoreBoard/GetChartBar.jsx, src/page/Vote/Components/ScoreBoard/VoteDataScore.jsx, src/page/Vote/ScoreBoard.jsx
- api 연결
- 투표를 선택하지 않고 들어왔을 때 에러문구띄우기
- ui 수정
#194
=> feat: 투표집계페이지

src/page/Vote/Components/VOTEHeader.jsx
- 직책, 조건에 따라 보이는 헤더 다르게 수정
- 현재 컨셉에 맞게 색상 수정
#194
=> feat: 투표의 헤더

src/page/Vote/Components/VOTEHeader.jsx
=> design: 투표의 헤더

src/page/Vote/Components/Submissions/CheckBox.jsx, src/page/Vote/Components/Submissions/CheckContent.jsx, src/page/Vote/Components/Submissions/RevisePeople.jsx, src/page/Vote/Components/Submissions/SubmitContentLG.jsx, src/page/Vote/Components/Submissions/SubmitContentMD.jsx, src/page/Vote/admin/Submissions.jsx
=> feat: 인원 관리 페이지

src/page/Clerk/Components/Research/CreateFormModal.jsx, src/page/Clerk/Components/Research/FormModal.jsx, src/page/Clerk/Components/Research/ResultModal.jsx, src/page/Clerk/Components/Research/research.css, src/page/Clerk/Research.jsx
=> feat:집계결과 열람 모달창 UI 구현

src/API/v1/clerk.js, src/API/v1/member.js, src/API/v1/vote.js, src/page/Board/Components/Boards.jsx, src/page/Board/Components/Comments.jsx, src/page/Board/Components/Content.jsx, src/page/Board/Components/FilesUploadForm.jsx, src/page/Board/Components/TextEditer.jsx, src/page/Board/Components/fileUploadForm.jsx, src/page/Clerk/Components/AutoAttend/Countdown.jsx, src/page/Clerk/Components/AutoAttend/DoAttend.jsx
=> fix: 서기페이지

src/page/Clerk/Components/Point/PointTable.jsx
- 상벌점 누계 페이지 상벌점과 총점이 분리되서 display되도록 수정
#213
=> style : css 수정

src/page/Clerk/Admin/TableOfAttend.jsx
=> fix: 세미나 출석 변경 페이지

src/page/Clerk/Admin/TableOfAttend.jsx, src/page/Clerk/Components/TableOfAttend/TableContent.jsx
=> fix: 세미나 출결 페이지

src/page/Clerk/AutoAttend.jsx
=> feat) 회원 인증코드 페이지 들어갈때 alert 뜨는 거 없앰

src/API/v1/clerk.js
=> fix) 날아간 api 복구 + 프리티어 적용

src/API/v1/member.js, src/App.jsx, src/page/Ranking/Component/RankingTable.jsx
- 자동 출석 성공하면 redux 업데이트 해 줌. 
#270
=> fix : 자동 출석시 redux 업데이트를 하지않아 db와 보유 포인트 차이나는 것 해결

src/API/v1/member.js, src/page/Game/Components/Dice.jsx, src/page/Game/Components/Lotto.jsx, src/page/Game/Game.jsx
- getMember api의 url의 수정이 반영이 안되서 생긴 문제여서 올바르게 고쳤다.
- 처음에 api를 이용해 받아오려고 하니 시간 차이가 있어서 redux의 member안에서 가져오는 것으로 바꾸었다.
#257
=> fix : 게임 보유포인트 안 보이는 에러 해결

src/API/v1/post.js, src/page/Board/Components/TextEditer.jsx, src/page/Board/Components/fileUploadForm.jsx
- 섬네일 안내 문구에 '드래그' 명시
- 포스팅 업로드 시 응답 객체 속성 조회에 옵셔널 체이닝 적용
#255
=> chore : 섬네일 문구 수정

src/App.jsx, src/shared/AuthUser.jsx
- 세션이 만료되어 로그아웃이 되었는데 로그인시 사용가능한 사이트에 남아있어서 작동이 안되는 문제이다.
- 세션이 만료되어 로그아웃되면 로그인 창으로 이동하게 만들었다. 
- #282
=> fix : 세션 만료 이후 처리

src/page/Attandance/Attandance.jsx
- 시차 상관없이 한국 시간 기준으로 출석 처리되도록
#156
=> fix : local 시간 한국 기준으로 변환

src/page/Profile/MyProfile.jsx
- api에서 isSpent가 1이면 음수로 보이도록 수정
#287
=> fix : 프로필 포인트 차감내역 음수로 보이도록

src/page/Ranking/Component/RankingTable.jsx, yarn.lock
잘못 머지된 거 새로 pr 생성해 올립니다.
- #267
=> Feature/랭킹 직책 띄우기 #267

src/page/CTF/Components/ChallengeModal.jsx
CTF overflow 처리한 것 운영서버 올라가기 전에 사용자들에게 직접적으로 보이는 곳에 있는 부분 먼저 수정해주기위해
문제명 흐르게 되어 있던 부분만 안 흐르도록 처리해주었습니다.
- #285
=> Feature/CTF 문제명 움직임 고정 #285

src/API/v1/ctf.js, src/page/CTF/Components/ChallengeCard.jsx, src/page/CTF/Components/ChallengeModal.jsx, src/page/CTF/Components/OtherTeamInfoModal.jsx, src/page/CTF/Team.jsx, src/page/CTF/admin/ChallengeAdmin.jsx, src/page/CTF/admin/ChallengeWrite.jsx
CTF 브루트포싱 방지를 위해
1. 문제 생성 시 최대 제출 횟수를 제출하도록 하고 문제에 남은 제출 횟수와 최대 제출 횟수를 보여주었습니다.
2. 플래그 제출 5초 내에 다시 플래그를 제출하지 못하도록 해당 문제의 마지막 제출 시간이 5초가 지나지 않았으면 API를 호출하지 못하도록 처리했습니다.
3. 추가적으로 팀 페이지와 다른 팀 정보를 조회할 때 문제를 해결한 시간을 표시해주었습니다.
- Closed #309
=> Feature/ctf 브루트포싱 방지 제출 횟수 제한 #309

src/page/CTF/admin/ChallengeWrite.jsx
- 문제 필수값 처리 안 되어 있는 상태에 저장되는 버그 픽스
- 비동기 관련 이슈
- Close #324
=> Feature/CTF 문제 생성 에러 문구 안뜸 에러 #324

src/page/CTF/admin/ChallengeWrite.jsx
- CTF 플래그 200자로 제한 변경 요구로 인해 글자수 제한 200자로 변경
- Close #327
=> Feature/CTF 글자수 제한 변경 #327

src/page/Profile/MyProfile.jsx, src/page/Profile/Profile.test.jsx
- 프로필 수정버튼이 랜더링 되는지 확인
- 프로필 수정버튼을 눌렀을 때 프로필 수정하기 텍스트가 보이는지 확인
- #303
=> feat : 프로필 수정버튼 테스트코드
